pipeline:
  build:
    image: registry.catvibers.me/ittai/builder
    commands:
      - pnpm i
      - ittai --plugin="./" --betterdiscord --powercordv2 --goosemod --production --output=./dist
    when:
      event: [ push ]

  setup:
    image: alpine/git
    commands:
      find . ! -name 'dist' -type d -exec rm -rf {} \;
      mv ./dist/* .
      rm -r ./dist
      git init

  push:
    image: appleboy/drone-git-push
    secrets: [git_ssh_key]
    settings:
      branch: build-gitea
      remote: git@git.catvibers.me:ittai/example-plugin.git
      force: false
      commit: true
      commit_message: Build plugin
      author_name: Ittai Builder [skip ci]
      author_email: ittai@catvibers.me
      ssh_key:
        from_secret: git_ssh_key

branches: main