pipeline:
  build:
    image: registry.catvibers.me/ittai/builder
    pull: true
    commands:
      - pnpm i
      - ittai --plugin="./" --betterdiscord=./dist --powercordv2=./dist --goosemod=./dist/goosemod --production
    when:
      event: [ push ]

  setup:
    image: alpine/git
    pull: true
    # TODO remove /tmp hack
    commands:
      - cp ./README* ./dist || true
      - cp ./LICENSE* ./dist || true
      - mv ./dist /tmp/dist
      - find . -path './*' -prune -exec rm -rf -- {} +
      - mv /tmp/dist/* .
      - git init
    when:
      event: [ push ]

  push:
    image: appleboy/drone-git-push
    pull: true
    secrets: [git_ssh_key]
    settings:
      branch: build-gitea
      remote: git@git.catvibers.me:ittai/example-plugin.git
      force: true
      commit: true
      commit_message: Build plugin
      author_name: ittaibot
      author_email: ittai@catvibers.me
      ssh_key:
        from_secret: git_ssh_key
    when:
      event: [ push ]

branches: main