pipeline:
  build:
    image: registry.catvibers.me/ittai/builder
    commands:
      - pnpm i
      - ittai --plugin="./" --betterdiscord --powercordv2 --goosemod --production --output=./dist
    when:
      event: [ push ]

  setup:
    image: alpine/git
    # TODO remove /tmp hack
    commands:
      - mv ./dist /tmp/dist
      - find . -path './*' -prune -exec rm -rf -- {} +
      - mv /tmp/dist/* .
      - git init

  push:
    image: appleboy/drone-git-push
    secrets: [git_ssh_key]
    settings:
      branch: build-gitea
      remote: git@git.catvibers.me:ittai/example-plugin.git
      force: true
      commit: true
      commit_message: Build plugin
      author_name: ittaibot
      author_email: ittai@catvibers.me
      ssh_key:
        from_secret: git_ssh_key

branches: main