name: Build Plugin
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        uses: docker://registry.catvibers.me/ittai/builder
        with:
          entrypoint: sh
          args: -c "pnpm i && ittai --plugin="./" --betterdiscord --powercordv2 --goosemod --production --output=./dist"

      - name: Prepare to push
        # TODO remove RUNNER_TEMP hack
        run: |
          mv ./dist $RUNNER_TEMP/dist
          find . -path './*' -prune -exec rm -rf -- {} +
          mv $RUNNER_TEMP/dist/* .
          git init
          git config --local user.email "ittai@catvibers.me"
          git config --local user.name "ittaibot"
          git commit -m "Build plugin" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: build-github
          force: true
